# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Rasila Gautam"

# A description of your site for meta tag, search engine results.
description: "Environmental Science Researcher | MSc Graduate from Tribhuvan University"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""  # leave this empty for GitHub Pages

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://rasila2.github.io"  # Your GitHub Pages URL

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Research
    url: /research/
  - text: Projects
    url: /projects/
  - text: Blogs
    url: /blogs/

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; 2025 Rasila Gautam. All rights reserved."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'

# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
